"""
Django settings for blog_project project.

Generated by 'django-admin startproject' using Django 4.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-1ivwlqyy$5km)jabq^9*-n167*-s5zx+l03&d)(*8r5nft8aqi'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 
    'blog',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'blog_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'blog_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# handling the images 

MEDIA_URL='/media/'

# MEDIA_ROOT=[ BASE_DIR / 'media']  iske bina bhi kam ho raha why ? use jya hai iska 

# STATICFILES_DIRS = (
#     [ BASE_DIR / 'static']
#     ) iske bina bhi kam ho raha why ?


# LOGIN_REDIRECT_URL=''
# LOGIN_REDIRECT_URL='home' 
# NoReverseMatch at /login/
# Reverse for '' not found. '' is not a valid view function or pattern name.

# LOGIN_REDIRECT_URL='blog/home'
# error
# Page not found (404)
# Request Method:	GET
# Request URL:	http://127.0.0.1:8000/login/blog/home
# LOGIN_REDIRECT_URL='form/'
# LOGIN_REDIRECT_URL='/form/'
# similar was the case with above two 

# LOGIN_REDIRECT_URL='blog-home'
# LOGIN_REDIRECT_URL='blog-form'

LOGIN_REDIRECT_URL='home'

# pahle wale home might be not working due to the terminal or technical issues 
# always close and restrat the terminal ,even if auto start and open a new tab 
# LOGIN_REDIRECT_URL='the name we have given to the path of a view , i.e what we have written in the name field of the path while writing the urls '


# Page not found (404)
# Request Method:	GET
# Request URL:	http://127.0.0.1:8000/accounts/login/?next=/profile/
# accounts/login/?next=/profile/  --> default location where the django looks for the login route 
# but since we have made our login roiutes we need to customize it 

LOGIN_URL='login'
# login is the name of the pattern that contain our login view OR login is the valueof the name atttribute  of the path of login 


# vrcel deployment
ALLOWED_HOSTS = ['.vercel.app','127.0.0.1'] # Allow *.vercel.app

# commenting out the databases for this 
# DATABASES = {}